### ISSUE TITLE
Error on "refresh account" in line 123

### ISSUE THREAD

**Issue by nbartels** [aaronk6/Kraken-MoneyMoney#8] opened 2021-05-10 12:47 UTC
I recently added the Kraken.lua script, connected everything, and it was working fine. After adding another cryptocurrency to my kraken account, it stopped working with the error message:

> Kraken.lua:123: attempt to index field '?' (a nil value)

**Comment by nbartels** [comment] 2021-05-10 12:53
After have a short look at the lua file, I think there are some cryptos missing. In this case it is DOGE (Dogecoin).

**Comment by aaronk6** [comment] 2021-05-17 16:22
> After have a short look at the lua file, I think there are some cryptos missing. In this case it is DOGE (Dogecoin).

I think this isn’t the cause of this error. The hard-coded currencies are just for displaying a nice currency name instead of the internal names (such as XETH). However, when a currency is returned from Kraken that is not in this look-up table, it will just display the key received from Kraken and shoudn’t fail.

Interestingly, I also have some Dogecoin in my Kraken account and don’t see this error. Can you provide the list of other cryptos (besides Dogecoin) that you have in your account, so I can try to reproduce the error? If you prefer, you can send it privately to my email: Kraken-MoneyMoney@dogespace.com (yes, I own this domain 🐶).

**Comment by aaronk6** [comment] 2021-05-17 21:57
Fixed in cd8f29719aa18208e9e4364089df550de3ade320.

**Closed by aaronk6** 2021-05-17 21:57 UTC
